// =====================================================================
//  DATOS DEL PLAN DE EQUIPO · Bandada · Mundial de Estudiantes 2026
//  Este es el unico archivo que hay que editar para actualizar la pagina.
//  1) Completen los nombres en EQUIPO (entre las comillas).
//  2) Si cambia una fecha, editen la tarea en TAREAS (formato AAAA-MM-DD).
// =====================================================================
window.BANDADA = {
  EQUIPO: {
    'COORD':  {nombre: '', rol: 'Coordinación General', foco: 'Integración, calendario, calidad y relación con el CLAM'},
    'MKT-L':  {nombre: '', rol: 'Líder de Marketing', foco: 'Modelo de negocio, precio y pitch deck'},
    'MKT-2':  {nombre: '', rol: 'Marketing · Investigación y clientes', foco: 'Entrevistas a productores y cartas de intención'},
    'MKT-3':  {nombre: '', rol: 'Marketing · Marca y web', foco: 'Identidad, manual de marca y web de reservas'},
    'RED-L':  {nombre: '', rol: 'Líder de Redes Sociales', foco: 'Calendario, métricas y voto del público'},
    'RED-2':  {nombre: '', rol: 'Redes · Contenido y diseño', foco: 'Cuentas, publicaciones e historias destacadas'},
    'RED-3':  {nombre: '', rol: 'Redes · Video y comunidad', foco: 'Reels y preinscripción de trabajadores'},
    'RRHH-L': {nombre: '', rol: 'Líder de Recursos Humanos', foco: 'Plan de RRHH, marco legal e impacto'},
    'RRHH-2': {nombre: '', rol: 'RRHH · Trabajadores y liderazgo', foco: 'Entrevistas a trabajadores y programa Jefe de Bandada'},
    'RRHH-3': {nombre: '', rol: 'RRHH · Políticas y cultura', foco: 'Contratación equitativa, cultura y valores'},
    'LOG-L':  {nombre: '', rol: 'Líder de Logística', foco: 'Piloto y expansión al MERCOSUR'},
    'LOG-2':  {nombre: '', rol: 'Logística · Calendario y capacidad', foco: 'Calendario de cosechas e inventario de jornadas'},
    'LOG-3':  {nombre: '', rol: 'Logística · Costos y traslados', foco: 'Costos por tramo, rutas y alojamiento'},
    'PRO-L':  {nombre: '', rol: 'Líder de Procesos Organizacionales', foco: 'Modelo financiero y banco de preguntas'},
    'PRO-2':  {nombre: '', rol: 'Procesos · Organización y flujos', foco: 'Organigrama, manual de funciones y flujograma'},
    'PRO-3':  {nombre: '', rol: 'Procesos · Blueprint y KPIs', foco: 'Service Blueprint, KPIs y apoyo en finanzas'},
  },

  AREAS: [
    {id: 'coord', nombre: 'Coordinación General', corto: 'Coordinación', lider: 'COORD', miembros: [],
      mision: 'Que todo llegue completo, coherente y a tiempo.',
      objetivo: 'Entregar la Etapa 2 completa, sin contradicciones y antes del plazo, y llegar a Mendoza con la defensa ensayada.',
      krs: ['100% de los entregables subidos el 28/10 antes de las 18:00',
            '0 cifras contradictorias entre documentos (control cruzado del 26 y 27/10)',
            '3 ensayos generales cronometrados, con jurado simulado y la rúbrica del Art. 10']},
    {id: 'mkt', nombre: 'Marketing', corto: 'Marketing', lider: 'MKT-L', miembros: ['MKT-2', 'MKT-3'],
      mision: 'Probar que productores y exportadores pagarían por Bandada, y contarlo con una marca sólida.',
      objetivo: 'Demostrar con evidencia propia que existe demanda dispuesta a pagar.',
      krs: ['7 entrevistas a productores, empacadoras o exportadores transcriptas',
            'Precio validado: 4 de cada 7 entrevistados aceptan un fee de entre 6% y 9%',
            '3 cartas de intención firmadas (junto con Logística)']},
    {id: 'red', nombre: 'Redes Sociales', corto: 'Redes', lider: 'RED-L', miembros: ['RED-2', 'RED-3'],
      mision: 'Construir comunidad y tracción real antes de la final, y ganar el voto del público.',
      objetivo: 'Llegar a la final con una comunidad real que respalde la idea.',
      krs: ['12 publicaciones, 4 reels y 4 historias destacadas publicados según el calendario',
            '100 trabajadores preinscriptos por Facebook o WhatsApp',
            '300 seguidores entre Instagram, LinkedIn y Facebook']},
    {id: 'rrhh', nombre: 'Recursos Humanos', corto: 'RRHH', lider: 'RRHH-L', miembros: ['RRHH-2', 'RRHH-3'],
      mision: 'Diseñar la gente de Bandada, dentro y fuera de la empresa, y validar la propuesta con los trabajadores.',
      objetivo: 'Que la propuesta para los trabajadores sea creíble, legal y justa.',
      krs: ['8 entrevistas a trabajadores y cabecillas de cuadrilla transcriptas',
            'Consulta con un abogado laboralista documentada antes del 16/10',
            'Plan de RRHH completo: dotación, contratación, capacitación y evaluación']},
    {id: 'log', nombre: 'Logística', corto: 'Logística', lider: 'LOG-L', miembros: ['LOG-2', 'LOG-3'],
      mision: 'Probar que el circuito anual se puede operar: tiempos, costos, traslados y alojamiento.',
      objetivo: 'Mostrar que el circuito anual funciona en la realidad, no solo en el papel.',
      krs: ['Calendario de 12 meses validado con 3 fuentes y 2 productores',
            'Costo real de traslado y alojamiento para 3 tramos del circuito',
            '1 cuadrilla colocada en el arándano de Tucumán, o 3 cartas de intención']},
    {id: 'pro', nombre: 'Procesos Organizacionales', corto: 'Procesos', lider: 'PRO-L', miembros: ['PRO-2', 'PRO-3'],
      mision: 'Que los números y los procesos resistan cualquier pregunta del jurado.',
      objetivo: 'Tener números y procesos que nadie del jurado pueda tumbar.',
      krs: ['Modelo financiero v2 a 3 años con supuestos tomados de las entrevistas',
            'Flujograma, cadena de valor, Service Blueprint y 10 KPIs con metas',
            'Banco de 30 preguntas difíciles con respuesta, ensayado por todas las áreas']},
  ],

  HITOS: [
    {fecha: '2026-10-05', titulo: 'Kickoff', detalle: 'Roles confirmados, disponibilidad cargada, canales y Drive listos.'},
    {fecha: '2026-10-10', titulo: 'Hito 1 · Cliente validado', detalle: 'Canvas v1, identidad lista, cuentas creadas y al menos 7 entrevistas hechas.'},
    {fecha: '2026-10-17', titulo: 'Hito 2 · Diseño v1', detalle: 'Finanzas v1, web online, organigrama, plan de RRHH v1, calendario y costos, 4 publicaciones.'},
    {fecha: '2026-10-24', titulo: 'Hito 3 · Congelamiento', detalle: 'Todos los entregables completos, finanzas v2 y resultado del piloto o las cartas de intención.'},
    {fecha: '2026-10-28', titulo: 'Entrega Etapa 2', detalle: 'Subir todo antes de las 18:00; el plazo vence a las 23:59.'},
    {fecha: '2026-11-05', titulo: 'Defensa final', detalle: 'Mendoza, cierre del CONAMERCO: 15 min de exposición y 10 de preguntas.'},
  ],

  SEMANAS: [
    {id: 'S1', desde: '2026-10-04', hasta: '2026-10-11', fase: 'Descubrir', nota: 'Entrevistas, identidad y bases del modelo'},
    {id: 'S2', desde: '2026-10-12', hasta: '2026-10-18', fase: 'Diseñar', nota: 'Lunes 12 es feriado. Versión 1 de todo.'},
    {id: 'S3', desde: '2026-10-19', hasta: '2026-10-25', fase: 'Validar e integrar', nota: 'Piloto, finanzas v2, congelamiento'},
    {id: 'S4', desde: '2026-10-26', hasta: '2026-11-01', fase: 'Cerrar y entregar', nota: 'Control de calidad y entrega el 28/10'},
    {id: 'S5', desde: '2026-11-02', hasta: '2026-11-05', fase: 'Defender', nota: 'Ensayos, viaje y final en Mendoza'},
  ],

  // id, area, tarea, responsable, apoyo, revisor (de otra area), inicio, vence, entregable
  TAREAS: [
    ['C1', 'coord', 'Kickoff: roles, disponibilidad y reglas de trabajo', 'COORD', '', 'Líderes', '2026-10-04', '2026-10-05', 'Organización interna'],
    ['C2', 'coord', 'Consulta escrita al CLAM: equipo de 16 integrantes y fecha de entrega (28 o 30/10)', 'COORD', '', 'Capitán', '2026-10-05', '2026-10-06', 'Cumplimiento del reglamento'],
    ['C3', 'coord', 'Drive, tablero de tareas, canales y plantillas de marca', 'COORD', 'MKT-3', 'Líderes', '2026-10-05', '2026-10-07', 'Organización interna'],
    ['C4', 'coord', 'Hoja de Supuestos maestros: la única fuente de cifras', 'COORD', 'PRO-L', 'Líderes', '2026-10-06', '2026-10-08', '9. Finanzas'],
    ['C5', 'coord', 'Revisiones de hito con todo el equipo (10, 17 y 24/10)', 'COORD', '', 'Capitán', '2026-10-10', '2026-10-24', 'Organización interna'],
    ['C6', 'coord', 'Control cruzado de cifras y mensajes entre entregables', 'COORD', 'PRO-L', 'Líderes', '2026-10-26', '2026-10-27', 'Todos'],
    ['C7', 'coord', 'Fuentes APA y declaración de IA en cada entregable (Arts. 24 y 28)', 'COORD', '', 'Líderes', '2026-10-26', '2026-10-27', 'Todos'],
    ['C8', 'coord', 'Envío de los entregables de la Etapa 2', 'COORD', '', 'Capitán', '2026-10-28', '2026-10-28', 'Todos'],
    ['C9', 'coord', 'Viaje a Mendoza: pasajes, alojamiento y acreditaciones', 'COORD', 'LOG-2', 'Capitán', '2026-10-29', '2026-11-03', 'Defensa final'],
    ['C10', 'coord', 'Ensayos generales con jurado simulado (31/10, 2/11 y 4/11)', 'COORD', 'PRO-L', 'Capitán', '2026-10-31', '2026-11-04', 'Defensa final'],

    ['M1', 'mkt', 'Entrevistas a productores, empacadoras y exportadores (7 de las 15)', 'MKT-2', 'MKT-L', 'RRHH-L', '2026-10-05', '2026-10-14', 'Customer discovery'],
    ['M2', 'mkt', 'Value Proposition Canvas por segmento', 'MKT-2', '', 'PRO-L', '2026-10-08', '2026-10-11', '1. Modelo de negocios'],
    ['M3', 'mkt', 'Business Model Canvas y Lean Canvas', 'MKT-L', '', 'PRO-L', '2026-10-08', '2026-10-13', '1. Modelo de negocios'],
    ['M4', 'mkt', 'TAM, SAM y SOM con fuentes', 'MKT-3', '', 'PRO-3', '2026-10-12', '2026-10-16', '1. Modelo de negocios'],
    ['M5', 'mkt', 'Identidad: logo, slogan y manual básico de marca', 'MKT-3', '', 'RED-L', '2026-10-05', '2026-10-11', '2. Identidad empresarial'],
    ['M6', 'mkt', 'Estrategia comercial y validación del precio (fee de 7%)', 'MKT-L', 'MKT-2', 'PRO-L', '2026-10-14', '2026-10-20', '1. Modelo de negocios'],
    ['M7', 'mkt', 'Web "Reservá tu cuadrilla": servicios, contacto, descripción y proceso de compra', 'MKT-3', '', 'PRO-2', '2026-10-12', '2026-10-20', '4. Comercio electrónico'],
    ['M8', 'mkt', 'Cartas de intención de productores (junto con Logística)', 'MKT-2', 'LOG-L', 'COORD', '2026-10-19', '2026-10-25', 'Tracción'],
    ['M9', 'mkt', 'Pitch deck de 10 a 12 slides', 'MKT-L', 'MKT-3', 'COORD', '2026-10-21', '2026-10-27', 'Defensa final'],

    ['R1', 'red', 'Crear Instagram, LinkedIn y Facebook con la identidad de marca', 'RED-2', '', 'MKT-L', '2026-10-08', '2026-10-12', '3. Marketing digital'],
    ['R2', 'red', 'Calendario de contenidos de 4 semanas', 'RED-L', '', 'MKT-L', '2026-10-08', '2026-10-11', '3. Marketing digital'],
    ['R3', 'red', '12 publicaciones (3 o 4 por semana)', 'RED-2', 'RED-L', 'MKT-3', '2026-10-12', '2026-10-27', '3. Marketing digital'],
    ['R4', 'red', '4 reels, incluido el video narrado en formato 9:16', 'RED-3', '', 'RED-L', '2026-10-12', '2026-10-26', '3. Marketing digital'],
    ['R5', 'red', '4 historias destacadas: Rutas, Jefes de Bandada, Cosecha Trazable y Preguntas', 'RED-2', '', 'RRHH-L', '2026-10-19', '2026-10-26', '3. Marketing digital'],
    ['R6', 'red', 'Campaña de preinscripción de trabajadores por Facebook y WhatsApp (meta: 100)', 'RED-3', 'RRHH-2', 'RRHH-L', '2026-10-12', '2026-10-25', 'Tracción'],
    ['R7', 'red', 'Métricas de redes para mostrar tracción en el pitch', 'RED-L', '', 'COORD', '2026-10-26', '2026-10-27', 'Defensa final'],
    ['R8', 'red', 'Demo con QR para el público y estrategia para el voto', 'RED-L', 'RED-3', 'COORD', '2026-10-29', '2026-11-04', 'Defensa final'],

    ['H1', 'rrhh', 'Entrevistas a trabajadores y cabecillas en Santiago del Estero (8 de las 15)', 'RRHH-2', 'RRHH-3', 'MKT-L', '2026-10-05', '2026-10-14', 'Customer discovery'],
    ['H2', 'rrhh', 'Consulta con abogado laboralista: Leyes 26.727, 27.742, 27.802 y decreto 514', 'RRHH-L', '', 'COORD', '2026-10-06', '2026-10-16', 'Riesgo legal'],
    ['H3', 'rrhh', 'Programa Jefe de Bandada: perfil, selección, incentivo y liderazgo', 'RRHH-2', '', 'PRO-L', '2026-10-12', '2026-10-18', '6. Recursos humanos'],
    ['H4', 'rrhh', 'Plan de RRHH: dotación inicial, contratación, capacitación y evaluación de desempeño', 'RRHH-L', 'RRHH-3', 'PRO-2', '2026-10-12', '2026-10-22', '6. Recursos humanos'],
    ['H5', 'rrhh', 'Política de contratación equitativa (OIT) y canal de reclamos', 'RRHH-3', '', 'LOG-L', '2026-10-15', '2026-10-20', '6. Recursos humanos'],
    ['H6', 'rrhh', 'Impacto económico, social y ambiental', 'RRHH-L', 'LOG-3', 'PRO-L', '2026-10-19', '2026-10-25', '10. Impacto social'],
    ['H7', 'rrhh', 'Cultura, valores y estrategia de liderazgo', 'RRHH-3', '', 'MKT-L', '2026-10-12', '2026-10-16', '5. Organización empresarial'],

    ['L1', 'log', 'Calendario de cosechas de 12 meses validado (fuentes y 2 productores)', 'LOG-2', '', 'MKT-2', '2026-10-05', '2026-10-13', '8. Logística'],
    ['L2', 'log', 'Costos reales por tramo: traslado (charter o pasaje) y alojamiento', 'LOG-3', '', 'PRO-L', '2026-10-08', '2026-10-16', '9. Finanzas'],
    ['L3', 'log', 'Cadena de abastecimiento e inventario de jornadas disponibles', 'LOG-2', '', 'PRO-2', '2026-10-12', '2026-10-20', '8. Logística'],
    ['L4', 'log', 'Plan de distribución: nodos de origen, destinos y rutas', 'LOG-3', '', 'RRHH-L', '2026-10-12', '2026-10-20', '8. Logística'],
    ['L5', 'log', 'Piloto: colocar 1 cuadrilla en el arándano de Tucumán o conseguir 3 cartas de intención', 'LOG-L', 'MKT-2', 'COORD', '2026-10-14', '2026-10-25', 'Tracción'],
    ['L6', 'log', 'Plan de expansión al MERCOSUR con marco CAGE', 'LOG-L', 'LOG-3', 'MKT-L', '2026-10-19', '2026-10-25', '8. Logística'],
    ['L7', 'log', 'Apoyo al viaje del equipo a Mendoza', 'LOG-2', '', 'COORD', '2026-10-29', '2026-11-03', 'Defensa final'],

    ['P1', 'pro', 'Organigrama, estructura y manual de funciones', 'PRO-2', '', 'RRHH-L', '2026-10-08', '2026-10-16', '5. Organización empresarial'],
    ['P2', 'pro', 'Flujograma general y cadena de valor', 'PRO-2', '', 'LOG-L', '2026-10-12', '2026-10-18', '7. Procesos'],
    ['P3', 'pro', 'Service Blueprint del viaje de una cuadrilla', 'PRO-3', '', 'LOG-L', '2026-10-15', '2026-10-21', '7. Procesos'],
    ['P4', 'pro', 'Tablero de 10 KPIs con metas', 'PRO-3', '', 'COORD', '2026-10-16', '2026-10-21', '7. Procesos'],
    ['P5', 'pro', 'Modelo financiero: inversión, costos, punto de equilibrio, flujo, 3 años y LTV/CAC (v1 17/10, v2 24/10)', 'PRO-L', 'PRO-3', 'COORD', '2026-10-08', '2026-10-24', '9. Finanzas'],
    ['P6', 'pro', 'Plan de crecimiento (junto con Logística)', 'PRO-2', 'LOG-L', 'MKT-L', '2026-10-19', '2026-10-23', '5. Organización empresarial'],
    ['P7', 'pro', 'Banco de 30 preguntas difíciles con respuestas (aportan todas las áreas)', 'PRO-L', 'COORD', 'Capitán', '2026-10-22', '2026-10-31', 'Defensa final'],
  ],

  // Reparto de los 15 minutos de la defensa (Art. 9) entre los 5 titulares
  DEFENSA: [
    {quien: 'MKT-L', min: 4, tema: 'Apertura con el tacho, problema, solución y modelo de negocio'},
    {quien: 'LOG-L', min: 3, tema: 'El circuito anual y la demo con QR'},
    {quien: 'RRHH-L', min: 2.5, tema: 'Personas, Jefes de Bandada e impacto'},
    {quien: 'PRO-L', min: 3, tema: 'Procesos, KPIs y números'},
    {quien: 'RED-L', min: 2.5, tema: 'Tracción, comunidad y cierre'},
  ],
};
